# Generated by Django 4.2.28 on 2026-02-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('results_available', 'Results Available'), ('results_expiring', 'Results Expiring Soon')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
            options={
                'unique_together': {('election', 'email_type')},
            },
        ),
    ]
