# Generated by Django 5.1.3 on 2026-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
